use crate::{cli::Cli, load, validate, generate, exec};
use crate::model::{ValidateSpec, RestartSpec};
use anyhow::{Context, Result};
use std::{fs, path::PathBuf, process::Command};

pub fn cmd_build(cli: &Cli) -> Result<()> {
    let loaded = load::load_all(&cli.config_dir)?;
    validate::validate_model(&loaded.domains, &loaded.upstreams, &loaded.policies, &loaded.defaults)?;

    let yaml_value = generate::generate_envoy_yaml(&loaded)?;

    fs::create_dir_all(&cli.out_dir)?;
    let out_path = cli.out_dir.join("envoy.generated.yaml");

    let header = format!(
        "# AUTO-GENERATED by envoyctl\n\
         # Edit fragments under: {}\n\
         # Output file: {}\n\n",
        cli.config_dir.display(),
        out_path.display(),
    );

    let body = serde_yaml::to_string(&yaml_value)?;
    fs::write(&out_path, format!("{header}{body}"))?;

    println!("Wrote {}", out_path.display());
    Ok(())
}

pub fn cmd_validate(cli: &Cli) -> Result<()> {
    cmd_build(cli)?;
    let loaded = load::load_all(&cli.config_dir)?;
    let out_path = cli.out_dir.join("envoy.generated.yaml");
    run_envoy_validate(cli, &loaded.runtime.validate, &out_path)?;
    println!("Validation OK");
    Ok(())
}

pub fn cmd_apply(cli: &Cli) -> Result<()> {
    cmd_validate(cli)?;
    let loaded = load::load_all(&cli.config_dir)?;

    let out_path = cli.out_dir.join("envoy.generated.yaml");
    atomic_install(&out_path, &cli.install_path)?;

    restart_envoy(&loaded.runtime.restart)?;
    println!("Applied and restarted Envoy");
    Ok(())
}

fn run_envoy_validate(cli: &Cli, validate: &ValidateSpec, generated: &PathBuf) -> Result<()> {
    match validate {
        ValidateSpec::Native {} => {
            let envoy = cli.envoy_bin.clone().unwrap_or_else(|| "envoy".to_string());
            let mut cmd = Command::new(envoy);
            cmd.args(["--mode", "validate", "-c"]).arg(generated);
            exec::run(&mut cmd).context("envoy validate (native)")?;
        }
        ValidateSpec::DockerImage { image } => {
            // docker run --rm -v <generated>:/cfg.yaml:ro <image> envoy --mode validate -c /cfg.yaml
            let abs = generated.canonicalize().context("canonicalize generated path")?;
            let mut cmd = Command::new("docker");
            cmd.args(["run", "--rm", "-v"])
                .arg(format!("{}:/cfg.yaml:ro", abs.display()))
                .arg(image)
                .args(["envoy", "--mode", "validate", "-c", "/cfg.yaml"]);
            exec::run(&mut cmd).context("envoy validate (docker image)")?;
        }
    }
    Ok(())
}

fn atomic_install(src: &PathBuf, dst: &PathBuf) -> Result<()> {
    let dir = dst.parent().context("install path has no parent")?;
    fs::create_dir_all(dir)?;
    let tmp = dir.join(format!(".{}.tmp", dst.file_name().unwrap().to_string_lossy()));
    fs::copy(src, &tmp)?;
    fs::rename(&tmp, dst)?;
    Ok(())
}

fn restart_envoy(restart: &RestartSpec) -> Result<()> {
    match restart {
        RestartSpec::DockerRestart { container } => {
            let mut cmd = Command::new("docker");
            cmd.args(["restart", container]);
            exec::run(&mut cmd).context("docker restart")?;
        }
        RestartSpec::DockerCompose { service, file } => {
            let mut cmd = Command::new("docker");
            cmd.arg("compose");
            if let Some(f) = file {
                cmd.args(["-f", f]);
            }
            cmd.args(["restart", service]);
            exec::run(&mut cmd).context("docker compose restart")?;
        }
    }
    Ok(())
}
