mod cli;
mod init;
mod model;
mod load;
mod validate;
mod generate;

use anyhow::Result;
use clap::Parser;
use cli::{Cli, Command};

fn main() -> Result<()> {
    let cli = Cli::parse();
    match &cli.cmd {
        Command::Init { dir } => init::cmd_init(&cli, dir),
        Command::Build => generate_config(&cli),
        Command::Validate => validate_config(&cli),
    }
}

fn generate_config(cli: &Cli) -> Result<()> {
    let loaded = load::load_all(&cli.config_dir)?;
    validate::validate_model(&loaded.domains, &loaded.upstreams, &loaded.policies, &loaded.defaults)?;

    let yaml_value = generate::generate_envoy_yaml(&loaded)?;

    std::fs::create_dir_all(&cli.out_dir)?;
    let out_path = cli.out_dir.join("envoy.generated.yaml");

    let header = format!(
        "# AUTO-GENERATED by envoyctl\n\
         # Edit fragments under: {}\n\
         # Output file: {}\n\n",
        cli.config_dir.display(),
        out_path.display(),
    );

    let body = serde_yaml::to_string(&yaml_value)?;
    std::fs::write(&out_path, format!("{header}{body}"))?;

    println!("Wrote {}", out_path.display());
    Ok(())
}

fn validate_config(cli: &Cli) -> Result<()> {
    generate_config(cli)?;
    println!("Validation OK - configuration generated successfully");
    Ok(())
}
